""" panel for Search engine """
import sys

from PyQt5.QtWidgets import QWidget, QApplication
from PyQt5 import QtCore, QtGui, QtWidgets

class SearchPage(QWidget):
    def __init__(self, parent=None):
        super(SearchPage, self).__init__(parent)

        self.setupUi(self)

    def setupUi(self, QWidget):
        QWidget.setObjectName("QWidget")
        QWidget.resize(787, 607)
        self.verticalLayout = QtWidgets.QVBoxLayout(QWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(QWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(QWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignLeft)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignLeft)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.verticalLayout_5.addWidget(self.tableWidget_2)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_7.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignLeft)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.verticalLayout_7.addWidget(self.tableWidget_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_9.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignLeft)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        self.verticalLayout_9.addWidget(self.tableWidget_4)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(QWidget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(QWidget)

    def retranslateUi(self, QWidget):
        _translate = QtCore.QCoreApplication.translate
        QWidget.setWindowTitle(_translate("QWidget", "QWidget"))
        self.pushButton.setText(_translate("QWidget", "Search"))
        self.pushButton_2.setText(_translate("QWidget", "Detail"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("QWidget", "User ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("QWidget", "User Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("QWidget", "User"))
        self.pushButton_3.setText(_translate("QWidget", "Detail"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("QWidget", "Team ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("QWidget", "Member 1"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("QWidget", "Member 2"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("QWidget", "Member 3"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("QWidget", "Member 4"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("QWidget", "Member 5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("QWidget", "Team"))
        self.pushButton_4.setText(_translate("QWidget", "Detail"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("QWidget", "Project Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("QWidget", "Individual Project"))
        self.pushButton_5.setText(_translate("QWidget", "PushButton"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("QWidget", "Project Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("QWidget", "Team Project"))

def main():
    cts = QApplication(sys.argv)
    mainWindow = SearchPage()
    mainWindow.show()
    # disable resize
    mainWindow.setFixedSize(1024, 648)
    sys.exit(cts.exec_())


main()
