from PyQt5.QtWidgets import QTabWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class SystemManager(QTabWidget):
    def __init__(self, parent=None):
        super(SystemManager, self).__init__(parent)

        self.setupUi(self)

    def setupUi(self, QTabWidget):
        QTabWidget.setObjectName("QTabWidget")
        QTabWidget.resize(797, 650)
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.widget1)
        QTabWidget.addTab(self.widget, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.tab)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setObjectName("widget_2")
        self.formLayout = QtWidgets.QFormLayout(self.widget_2)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_4)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_8)
        self.horizontalLayout_2.addWidget(self.widget_2)
        QTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_6 = QtWidgets.QWidget(self.tab_2)
        self.widget_6.setObjectName("widget_6")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget_6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_7 = QtWidgets.QLabel(self.widget_6)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_8 = QtWidgets.QLabel(self.widget_6)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.widget_4 = QtWidgets.QWidget(self.tab_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.widget_4)
        QTabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.tableWidget_4)
        self.widget_5 = QtWidgets.QWidget(self.tab_3)
        self.widget_5.setObjectName("widget_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7, 0, QtCore.Qt.AlignHCenter)
        QTabWidget.addTab(self.tab_3, "")

        self.retranslateUi(QTabWidget)
        QTabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(QTabWidget)

    def retranslateUi(self, QTabWidget):
        _translate = QtCore.QCoreApplication.translate
        QTabWidget.setWindowTitle(_translate("QTabWidget", "QTabWidget"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("QTabWidget", "User ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("QTabWidget", "User Type"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("QTabWidget", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("QTabWidget", "Adress"))
        self.pushButton.setText(_translate("QTabWidget", "Accept"))
        self.pushButton_2.setText(_translate("QTabWidget", "Reject"))
        QTabWidget.setTabText(QTabWidget.indexOf(self.widget), _translate("QTabWidget", "Application"))
        self.label.setText(_translate("QTabWidget", "Blacklist"))
        self.pushButton_3.setText(_translate("QTabWidget", "Remove User From Blacklist"))
        self.label_2.setText(_translate("QTabWidget", "Add this user to blacklist"))
        self.pushButton_4.setText(_translate("QTabWidget", "Add to blacklist"))
        self.label_5.setText(_translate("QTabWidget", "TextLabel"))
        self.pushButton_8.setText(_translate("QTabWidget", "Remove 1 warn from this user"))
        QTabWidget.setTabText(QTabWidget.indexOf(self.tab), _translate("QTabWidget", "Blacklist"))
        self.label_6.setText(_translate("QTabWidget", "Send From"))
        self.label_7.setText(_translate("QTabWidget", "Send To"))
        self.label_8.setText(_translate("QTabWidget", "Amount"))
        self.pushButton_5.setText(_translate("QTabWidget", "Post"))
        QTabWidget.setTabText(QTabWidget.indexOf(self.tab_2), _translate("QTabWidget", "Transaction"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("QTabWidget", "Project Name"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("QTabWidget", "Sender ID"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("QTabWidget", "Receiver ID"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("QTabWidget", "New Column"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("QTabWidget", "Rating"))
        self.label_3.setText(_translate("QTabWidget", "Change review to:"))
        self.label_4.setText(_translate("QTabWidget", "Change rating to"))
        self.pushButton_7.setText(_translate("QTabWidget", "Submit Change"))
        QTabWidget.setTabText(QTabWidget.indexOf(self.tab_3), _translate("QTabWidget", "User Review"))

