from PyQt5.QtWidgets import QWidget, QApplication
from PyQt5 import QtCore, QtGui, QtWidgets


class TeamPage(QWidget):
    def __init__(self, parent=None):
        super(TeamPage, self).__init__(parent)

        self.setupUi(self)

    def setupUi(self, QWidget):
        QWidget.setObjectName("QWidget")
        QWidget.resize(798, 569)
        self.tableWidget = QtWidgets.QTableWidget(QWidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 761, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(QWidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 230, 761, 181))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.label = QtWidgets.QLabel(QWidget)
        self.label.setGeometry(QtCore.QRect(20, 430, 71, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(QWidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 430, 611, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(QWidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 460, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(QWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 500, 111, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(QWidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 500, 611, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(QWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 530, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(QWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 200, 111, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(QWidget)
        QtCore.QMetaObject.connectSlotsByName(QWidget)

    def retranslateUi(self, QWidget):
        _translate = QtCore.QCoreApplication.translate
        QWidget.setWindowTitle(_translate("QWidget", "QWidget"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("QWidget", "Team Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("QWidget", "Member1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("QWidget", "Member2"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("QWidget", "Member3"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("QWidget", "Member4"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("QWidget", "Member5"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("QWidget", "Project id"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("QWidget", "Client"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("QWidget", "Price"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("QWidget", "Due date"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("QWidget", "Detail"))
        self.label.setText(_translate("QWidget", "Join a team"))
        self.pushButton.setText(_translate("QWidget", "Join"))
        self.label_2.setText(_translate("QWidget", "Create a team"))
        self.pushButton_2.setText(_translate("QWidget", "Create"))
        self.pushButton_3.setText(_translate("QWidget", "Review this member"))