""" page for showing the top3 clients and developers"""

from PyQt5.QtWidgets import QWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Top3(QWidget):
    def __init__(self, parent=None):
        super(Top3, self).__init__(parent)

        self.setupUi(self)

    def setupUi(self, QWidget):
        QWidget.setObjectName("QWidget")
        QWidget.resize(884, 648)
        self.verticalLayout = QtWidgets.QVBoxLayout(QWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(QWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_2 = QtWidgets.QLabel(QWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.widget_3 = QtWidgets.QWidget(QWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(60, 90, 71, 61))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(190, 110, 201, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(190, 230, 201, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(60, 210, 71, 61))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(190, 350, 201, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(60, 330, 71, 61))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setObjectName("widget")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setGeometry(QtCore.QRect(180, 350, 201, 21))
        self.label_14.setObjectName("label_14")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(50, 90, 71, 61))
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(180, 110, 201, 21))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(50, 210, 71, 61))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(180, 230, 201, 21))
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(50, 330, 71, 61))
        self.label_9.setObjectName("label_9")
        self.widget_2.raise_()
        self.label_14.raise_()
        self.label_11.raise_()
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_9.raise_()
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(QWidget)
        QtCore.QMetaObject.connectSlotsByName(QWidget)

    def retranslateUi(self, QWidget):
        _translate = QtCore.QCoreApplication.translate
        QWidget.setWindowTitle(_translate("QWidget", "QWidget"))
        self.label.setText(_translate("QWidget", "TOP 3"))
        self.label_2.setText(_translate("QWidget",
                                        "       Clients With Most Projects:                                                                                                               Developers Making Most Money"))
        self.label_3.setText(_translate("QWidget", "Client1"))
        self.label_4.setText(_translate("QWidget", "ClientID1"))
        self.label_5.setText(_translate("QWidget", "ClientID2"))
        self.label_6.setText(_translate("QWidget", "Client2"))
        self.label_7.setText(_translate("QWidget", "ClientID3"))
        self.label_8.setText(_translate("QWidget", "Client3"))
        self.label_14.setText(_translate("QWidget", "DevID3"))
        self.label_11.setText(_translate("QWidget", "Dev1"))
        self.label_10.setText(_translate("QWidget", "DevID1"))
        self.label_12.setText(_translate("QWidget", "Dev2"))
        self.label_13.setText(_translate("QWidget", "DevID2"))
        self.label_9.setText(_translate("QWidget", "Dev3"))
